In [2]:
import numpy as np
X = np.array([[1, 0.74826, 0.74826, 0.45158],[1, 0.81465, 0.27117, 0.33121], [1, 0.71177, 0.09633, 0.71177], [1, 0.88250, 0.16122, 0.65377]])

z = [[0.8], [0.6],[ 0.3], [0.3]]

transposeX = np.transpose(X)

#inverse of matrix X
inverseX =	np.linalg.inv(X)
# print("Inverse of X: \n", inverseX)

#calculate the dot product between X and transposeX
dotProduct = np.dot(transposeX, X)
# print("Dot product of X and transposeX: \n", dotProduct)

# calculate dotProduct + 0.1I
I = np.eye(4)
r1 = dotProduct + (0.1 * I)
# print("Dot product + 0.1I: \n", r1)

#inverse of r1
inverseR1 = np.linalg.inv(r1)
print("Inverse of r1: \n", inverseR1)

# inverseR1 dot product transposeX
r2 = np.dot(inverseR1, transposeX)
print("r2: \n", r2)

final = np.dot(r2, z)
print("Final: \n", final)



Inverse of r1: 
 [[ 4.63988465 -3.84925752 -1.12818079 -2.06209656]
 [-3.84925752  5.86330545 -0.32701128 -1.07616986]
 [-1.12818079 -0.32701128  2.87144251  0.9268595 ]
 [-2.06209656 -1.07616986  0.9268595   4.9660326 ]]
r2: 
 [[-0.01573491  0.51517123  0.3236825  -0.28710729]
 [-0.19264683  0.4821704  -0.47341902  0.56882121]
 [ 1.19426653 -0.30894633 -0.42462077 -0.34788135]
 [ 0.06874147 -1.04266219  0.79587542  0.38425496]]
Final: 
 [[ 0.30748738]
 [ 0.16380543]
 [ 0.53829479]
 [-0.21656503]]


In [3]:
import numpy as np

w1 = np.array([[1, 1, 1, 1], [1, 1, 2, 1], [1, 1, 1, 1]])
x01 = np.array([[1], [1], [1], [1]])
b1 = np.array([[1], [1], [1]])
b2 = np.array([[1], [1]])
w2 = np.array([[1, 4, 1], [1, 1, 1]])
b3 = np.array([[1], [1], [1]])
w3 = np.array([[1, 1], [3, 1], [1, 1]])
x02 = np.array([[1], [0], [0], [-1]])

t_x1 = np.array([[-1], [1], [-1]])

#for x1
z1 = np.dot(w1, x01) + b1
# print("z1: \n", z1)

#tanh activation function f(x)= tanh(0.5x -2)
x1 = np.tanh(0.5 * z1 - 2)
# print("x1: \n", x1)

z2 = np.dot(w2, x1) + b2
# print("z2: \n", z2)

x2 = np.tanh(0.5 * z2 - 2)
# print("x2: \n", x2)

z3 = np.dot(w3, x2) + b3
# print("z3: \n", z3)


x3 = np.tanh(0.5 * z3 - 2)
# print("x3: \n", x3)



# 2*cosh(0.5z3 -2)^2

d3 = 2*np.cosh(0.5*z3 -2)**2

res = 1/d3
# print("res: \n", res)

res1 = x3 - t_x1


#hadamard product between res and res1
delta3 = res1 * res
# print("lamda3: \n", lamda3)

Ew3 = np.dot(delta3, np.transpose(x2))
# print("Ew3: \n", Ew3)

newW3 = w3 - 0.1*Ew3
# print("newW3: \n", newW3)

newB3 = b3 - 0.1*delta3
# print("newB3: \n", newB3)

d2 = 2*np.cosh(0.5*z2 -2)**2
d2r = 1/d2
# print("d2r: \n", d2r)

delta2 = np.dot(np.transpose(w3), delta3) * d2r
# print("delta2: \n", delta2)

Ew2 = np.dot(delta2, np.transpose(x1))
# print("Ew2: \n", Ew2)

newW2 = w2 - 0.1*Ew2
# print("newW2: \n", newW2)

newB2 = b2 - 0.1*delta2
# print("newB2: \n", newB2)

#----------
d3 = 2*np.cosh(0.5*z1 -2)**2
d3r = 1/d3
# print("d3r: \n", d3r)

delta1 = np.dot(np.transpose(w2), delta2) * d3r
# print("delta1: \n", delta1)

Ew1 = np.dot(delta1, np.transpose(x01))
# print("Ew1: \n", Ew1)

newW1 = w1 - 0.1*Ew1
# print("newW1: \n", newW1)

newB1 = b1 - 0.1*delta1
print("newB1: \n", newB1)

newB1: 
 [[1.01871904]
 [1.03358719]
 [1.01871904]]


In [23]:
# same process for x2
#for x1
# print("x02: \n", x02)

x02 = np.array([[1], [0], [0], [-1]])
t_x2 = np.array([[1], [-1], [-1]])
# print("t_x2: \n", t_x2)

z1 = np.dot(w1, x02) + b1
# print("z1: \n", z1)

#tanh activation function f(x)= tanh(0.5x -2)
x1 = np.tanh(0.5 * z1 - 2)
# print("x1: \n", x1)

z2 = np.dot(w2, x1) + b2
# print("z2: \n", z2)

x2 = np.tanh(0.5 * z2 - 2)
# print("x2: \n", x2)

z3 = np.dot(w3, x2) + b3
# print("z3: \n", z3)


x3 = np.tanh(0.5 * z3 - 2)
# print("x3: \n", x3) 



# 2*cosh(0.5z3 -2)^2

d3 = 2*np.cosh(0.5*z3 -2)**2

res = 1/d3
# print("res: \n", res)

res1 = x3 - t_x2
# print("res1: \n", res1)


#hadamard product between res and res1
delta3 = res1 * res
# print("lamda3: \n", delta3)

Ew3 = np.dot(delta3, np.transpose(x2))
# print("Ew3: \n", Ew3)

# print("w3: \n", w3)
newW3 = w3 - 0.1*Ew3
# print("newW3: \n", newW3)

newB3 = b3 - 0.1*delta3
# print("newB3: \n", newB3)

#---------------

d2 = 2*np.cosh(0.5*z2 -2)**2
d2r = 1/d2
# print("d2r: \n", d2r)

delta2 = np.dot(np.transpose(w3), delta3) * d2r
# print("delta2: \n", delta2)

Ew2 = np.dot(delta2, np.transpose(x1))
# print("Ew2: \n", Ew2)

newW2 = w2 - 0.1*Ew2
# print("newW2: \n", newW2)

newB2 = b2 - 0.1*delta2
# print("newB2: \n", newB2)

#----------
d3 = 2*np.cosh(0.5*z1 -2)**2
d3r = 1/d3
print("d3r: \n", d3r)

delta1 = np.dot(np.transpose(w2), delta2) * d3r
print("delta1: \n", delta1)

Ew1 = np.dot(delta1, np.transpose(x02))
print("Ew1: \n", Ew1)

newW1 = w1 - 0.1*Ew1
print("newW1: \n", newW1)

newB1 = b1 - 0.1*delta1
print("newB1: \n", newB1)

d3r: 
 [[0.09035332]
 [0.09035332]
 [0.09035332]]
delta1: 
 [[-1.66619254e-05]
 [-1.97816249e-05]
 [-1.66619254e-05]]
Ew1: 
 [[-1.66619254e-05  0.00000000e+00  0.00000000e+00  1.66619254e-05]
 [-1.97816249e-05  0.00000000e+00  0.00000000e+00  1.97816249e-05]
 [-1.66619254e-05  0.00000000e+00  0.00000000e+00  1.66619254e-05]]
newW1: 
 [[1.00000167 1.         1.         0.99999833]
 [1.00000198 1.         2.         0.99999802]
 [1.00000167 1.         1.         0.99999833]]
newB1: 
 [[1.00000167]
 [1.00000198]
 [1.00000167]]
